/* NetHack 5.0  mkglyphhash.c
 *
 * Build-time host tool: emit src/glyph_hashes.c containing the canonical
 * G_xxx hash for every glyph, indexed by glyph number.
 *
 * The runtime resolver (glyph_find_core) hashes the user-supplied id once,
 * scans this table, and verifies any match by reconstructing the canonical
 * name via compose_glyph_name() and strcmpi'ing it back.  No runtime cache,
 * no allocations, suitable for memory-tight ports.
 */

#include "hack.h"

extern void monst_globals_init(void);
extern void objects_globals_init(void);

/* compose_glyph_name() resolves cmap base names through loadsyms[],
 * monster names through monsdump[], object names through obj_descr[].
 * Provide minimal copies of the data arrays in this translation unit
 * (they're trivial macro expansions of header files) so the host tool
 * doesn't have to drag earlyarg.o / symbols.o / utf8map.o, and their
 * runtime deps, into its link. */
const struct symparse loadsyms[] = {
    { SYM_CONTROL, 0, "start" },
#define PCHAR_PARSE
#include "defsym.h"
#undef PCHAR_PARSE
    { SYM_INVALID, 0, (const char *) 0 },
};

#define DUMP_ENUMS
struct enum_dump monsdump[] = {
#include "monsters.h"
    { NUMMONS, "NUMMONS" },
    { NON_PM, "NON_PM" },
    { LOW_PM, "LOW_PM" },
    { HIGH_PM, "HIGH_PM" },
    { SPECIAL_PM, "SPECIAL_PM" }
};
struct enum_dump objdump[] = {
#include "objects.h"
    { NUM_OBJECTS, "NUM_OBJECTS" },
};
#undef DUMP_ENUMS

#define BUFSZ_LOCAL 256

int
main(int argc, char *argv[])
{
    int glyph;
    char buf[BUFSZ_LOCAL];
    const char *outname;
    FILE *ofp;

    if (argc < 2) {
        fprintf(stderr, "usage: %s <output-file>\n", argv[0]);
        return EXIT_FAILURE;
    }
    outname = argv[1];

    objects_globals_init();
    monst_globals_init();

    ofp = fopen(outname, "w");
    if (!ofp) {
        perror(outname);
        return EXIT_FAILURE;
    }

    fprintf(ofp, "/* This file is automatically generated.  Do not edit. */\n");
    fprintf(ofp, "/* Generated by util/mkglyphhash. */\n\n");
    fprintf(ofp, "#include \"hack.h\"\n\n");
    fprintf(ofp,
            "/* Hash of each glyph's canonical \"G_xxx\" identifier (post\n"
            " * fix_glyphname normalisation).  0 indicates a glyph with no\n"
            " * canonical name (a few unused object slots).  Runtime lookup\n"
            " * hashes the input and linear-scans this table; collisions are\n"
            " * disambiguated by reconstructing the name and string-comparing. */\n");
    fprintf(ofp, "const uint32 glyph_name_hashes[MAX_GLYPH] = {\n");

    for (glyph = 0; glyph < MAX_GLYPH; ++glyph) {
        if (compose_glyph_name(glyph, buf, sizeof buf)) {
            uint32 h = glyph_name_hash(buf);
            fprintf(ofp, "    0x%08lxUL, /* [%04d] %s */\n",
                    (unsigned long) h, glyph, buf);
        } else {
            fprintf(ofp, "    0UL,         /* [%04d] <no name> */\n", glyph);
        }
    }

    fprintf(ofp, "};\n\n/*glyph_hashes.c*/\n");
    fclose(ofp);
    return EXIT_SUCCESS;
}
