/* NetHack 5.0  mkglyphhash.c
 *
 * Build-time host tool: emit src/glyph_hashes.c containing a sorted
 * (hash, glyph) index of canonical G_xxx identifiers.
 *
 * The runtime resolver (glyph_find_core) hashes the user-supplied id,
 * bsearches this index, and verifies any hash match by reconstructing
 * the canonical name via compose_glyph_name() and strcmpi'ing it back.
 * O(log N) lookup, zero runtime allocations.
 */

#include "hack.h"

extern void monst_globals_init(void);
extern void objects_globals_init(void);

/* compose_glyph_name() resolves cmap base names through loadsyms[],
 * monster names through monsdump[], object names through obj_descr[].
 * Provide minimal copies of the data arrays in this translation unit
 * (they're trivial macro expansions of header files) so the host tool
 * doesn't have to drag earlyarg.o / symbols.o / utf8map.o, and their
 * runtime deps, into its link. */
const struct symparse loadsyms[] = {
    { SYM_CONTROL, 0, "start" },
#define PCHAR_PARSE
#include "defsym.h"
#undef PCHAR_PARSE
    { SYM_INVALID, 0, (const char *) 0 },
};

#define DUMP_ENUMS
struct enum_dump monsdump[] = {
#include "monsters.h"
    { NUMMONS, "NUMMONS" },
    { NON_PM, "NON_PM" },
    { LOW_PM, "LOW_PM" },
    { HIGH_PM, "HIGH_PM" },
    { SPECIAL_PM, "SPECIAL_PM" }
};
struct enum_dump objdump[] = {
#include "objects.h"
    { NUM_OBJECTS, "NUM_OBJECTS" },
};
#undef DUMP_ENUMS

#define BUFSZ_LOCAL 256

struct entry {
    uint32 hash;
    uint16 glyph;
};

static int
cmp_entry(const void *a, const void *b)
{
    uint32 ha = ((const struct entry *) a)->hash;
    uint32 hb = ((const struct entry *) b)->hash;

    if (ha < hb)
        return -1;
    if (ha > hb)
        return 1;
    /* tiebreak by glyph number so output is deterministic on hash collisions */
    return (int) ((const struct entry *) a)->glyph
           - (int) ((const struct entry *) b)->glyph;
}

int
main(int argc, char *argv[])
{
    int glyph;
    unsigned i, n = 0;
    char buf[BUFSZ_LOCAL];
    const char *outname;
    FILE *ofp;
    struct entry *entries;

    if (argc < 2) {
        fprintf(stderr, "usage: %s <output-file>\n", argv[0]);
        return EXIT_FAILURE;
    }
    outname = argv[1];

    objects_globals_init();
    monst_globals_init();

    entries = (struct entry *) malloc(MAX_GLYPH * sizeof *entries);
    if (!entries) {
        fprintf(stderr, "%s: out of memory\n", argv[0]);
        return EXIT_FAILURE;
    }
    for (glyph = 0; glyph < MAX_GLYPH; ++glyph) {
        if (compose_glyph_name(glyph, buf, sizeof buf)) {
            entries[n].hash = glyph_name_hash(buf);
            entries[n].glyph = (uint16) glyph;
            ++n;
        }
    }
    qsort(entries, n, sizeof entries[0], cmp_entry);

    ofp = fopen(outname, "w");
    if (!ofp) {
        perror(outname);
        free(entries);
        return EXIT_FAILURE;
    }

    fprintf(ofp, "/* This file is automatically generated.  Do not edit. */\n");
    fprintf(ofp, "/* Generated by util/mkglyphhash. */\n\n");
    fprintf(ofp, "#include \"hack.h\"\n\n");
    fprintf(ofp,
            "/* Sorted (hash, glyph) index of canonical G_xxx identifiers.\n"
            " * Runtime lookup hashes the input id and binary-searches\n"
            " * glyph_hash_index_hash[]; hash collisions (rare) are\n"
            " * disambiguated by reconstructing each candidate's name\n"
            " * and string-comparing.  Generated by util/mkglyphhash. */\n\n");
    fprintf(ofp, "const unsigned glyph_hash_index_count = %u;\n\n", n);

    fprintf(ofp, "const uint32 glyph_hash_index_hash[%u] = {\n", n);
    for (i = 0; i < n; ++i) {
        compose_glyph_name((int) entries[i].glyph, buf, sizeof buf);
        fprintf(ofp, "    0x%08lxUL, /* [%04u] %s */\n",
                (unsigned long) entries[i].hash,
                (unsigned) entries[i].glyph, buf);
    }
    fprintf(ofp, "};\n\n");

    fprintf(ofp, "const uint16 glyph_hash_index_glyph[%u] = {\n", n);
    for (i = 0; i < n; ++i)
        fprintf(ofp, "    %u,\n", (unsigned) entries[i].glyph);
    fprintf(ofp, "};\n\n/*glyph_hashes.c*/\n");
    fclose(ofp);
    free(entries);
    return EXIT_SUCCESS;
}
